// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8TLaEMBl1O5SmYYbggAPfSVwHys5qvY',
    appId: '1:472864149450:web:9772808a9e1c256a128933',
    messagingSenderId: '472864149450',
    projectId: 'fir-fb641',
    authDomain: 'fir-fb641.firebaseapp.com',
    storageBucket: 'fir-fb641.firebasestorage.app',
    measurementId: 'G-MEASUREMENT-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE8TLaEMBl1O5SmYYbggAPfSVwHys5qvY',
    appId: '1:472864149450:android:9772808a9e1c256a128933',
    messagingSenderId: '472864149450',
    projectId: 'fir-fb641',
    storageBucket: 'fir-fb641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8TLaEMBl1O5SmYYbggAPfSVwHys5qvY',
    appId: '1:472864149450:ios:6voqo9js3ul3ctkrl8ipbsr87tu6vo64',
    messagingSenderId: '472864149450',
    projectId: 'fir-fb641',
    storageBucket: 'fir-fb641.firebasestorage.app',
    iosBundleId: 'com.example.ioe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE8TLaEMBl1O5SmYYbggAPfSVwHys5qvY',
    appId: '1:472864149450:ios:6voqo9js3ul3ctkrl8ipbsr87tu6vo64',
    messagingSenderId: '472864149450',
    projectId: 'fir-fb641',
    storageBucket: 'fir-fb641.firebasestorage.app',
    iosBundleId: 'com.example.ioe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE8TLaEMBl1O5SmYYbggAPfSVwHys5qvY',
    appId: '1:472864149450:web:9772808a9e1c256a128933',
    messagingSenderId: '472864149450',
    projectId: 'fir-fb641',
    authDomain: 'fir-fb641.firebaseapp.com',
    storageBucket: 'fir-fb641.firebasestorage.app',
    measurementId: 'G-MEASUREMENT-ID',
  );
}
