// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-gXYoOd5wpPVpqLt3tyg11jRVia1zkM',
    appId: '1:823890766557:web:12940ce56df040939dc934',
    messagingSenderId: '823890766557',
    projectId: 'attendance-2ee31',
    authDomain: 'attendance-2ee31.firebaseapp.com',
    storageBucket: 'attendance-2ee31.firebasestorage.app',
    measurementId: 'G-WEH0LRTQVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18ZpphQ3kkSzNoiJrG2CGr5ObtICSD5U',
    appId: '1:823890766557:android:d29939f64d05e7699dc934',
    messagingSenderId: '823890766557',
    projectId: 'attendance-2ee31',
    storageBucket: 'attendance-2ee31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOby_-N-CVaNYN_S8vJzMlMHsR4wBu9Co',
    appId: '1:823890766557:ios:1cfd720e6f078c079dc934',
    messagingSenderId: '823890766557',
    projectId: 'attendance-2ee31',
    storageBucket: 'attendance-2ee31.firebasestorage.app',
    iosBundleId: 'com.example.ioe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOby_-N-CVaNYN_S8vJzMlMHsR4wBu9Co',
    appId: '1:823890766557:ios:1cfd720e6f078c079dc934',
    messagingSenderId: '823890766557',
    projectId: 'attendance-2ee31',
    storageBucket: 'attendance-2ee31.firebasestorage.app',
    iosBundleId: 'com.example.ioe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-gXYoOd5wpPVpqLt3tyg11jRVia1zkM',
    appId: '1:823890766557:web:e6ccf0994f48408b9dc934',
    messagingSenderId: '823890766557',
    projectId: 'attendance-2ee31',
    authDomain: 'attendance-2ee31.firebaseapp.com',
    storageBucket: 'attendance-2ee31.firebasestorage.app',
    measurementId: 'G-JLG6PK4TWQ',
  );
}
